# Generated by Django 5.1.2 on 2024-10-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifimodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.CharField(max_length=255)),
                ('sayi', models.IntegerField(blank=True, null=True)),
                ('sicaklik', models.FloatField(blank=True, null=True)),
                ('nem', models.FloatField(blank=True, null=True)),
                ('uzaklik', models.FloatField(blank=True, null=True)),
                ('role', models.BooleanField(default=False)),
                ('led', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TextData',
        ),
    ]
