# Generated by Django 5.1.2 on 2024-10-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifimodule', '0004_textdata_delete_sensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
