# Generated by Django 5.1.2 on 2024-11-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifimodule', '0005_distancedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumidityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
