# Generated by Django 5.1.2 on 2025-01-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifimodule', '0007_buzzerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
